#!/usr/bin/env python3
"""Generate the markdown body for the weekly citations digest GitHub Issue.

Prints the digest to stdout. The calling workflow should open an issue only
if stdout is non-empty. Exits 0 with empty output when:
  - config.weekly_digest is false
  - no non-bootstrap citations were seen in the last 7 days
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config.json"
PROFILE_PATH = ROOT / "data" / "profile.json"
PAPERS_PATH = ROOT / "data" / "papers.json"
CITATIONS_PATH = ROOT / "data" / "citations.jsonl"


def load_json(path: Path, default):
    if not path.exists():
        return default
    return json.loads(path.read_text())


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def surname(name: str) -> str:
    parts = (name or "").strip().split()
    return parts[-1] if parts else ""


def is_self_citation(citing_authors: str, surname_re: re.Pattern | None) -> bool:
    if not surname_re:
        return False
    return bool(surname_re.search(citing_authors or ""))


def main() -> int:
    config = load_json(CONFIG_PATH, {})
    if not config.get("weekly_digest", True):
        return 0  # feature disabled; no output

    profile = load_json(PROFILE_PATH, {}) or {}
    papers = load_json(PAPERS_PATH, []) or []
    citations = load_jsonl(CITATIONS_PATH)

    today = date.today()
    week_ago = today - timedelta(days=7)
    start = week_ago.isoformat()
    end = today.isoformat()

    prof_surname = surname(profile.get("name", ""))
    surname_re = re.compile(rf"\b{re.escape(prof_surname)}\b", re.IGNORECASE) if prof_surname else None

    papers_by_id = {p["id"]: p for p in papers}

    # Filter last-7-day non-bootstrap citations.
    windowed = [
        row for row in citations
        if not row.get("bootstrap")
        and start <= row.get("first_seen_date", "") <= end
    ]

    total = len(windowed)
    self_cites = sum(1 for row in windowed if is_self_citation(row.get("citing_authors", ""), surname_re))
    non_self = total - self_cites

    if total == 0:
        return 0  # nothing to report; caller will skip issue creation

    by_paper: dict[str, list[dict]] = defaultdict(list)
    for row in windowed:
        by_paper[row["paper_id"]].append(row)

    ranked = sorted(by_paper.items(), key=lambda kv: -len(kv[1]))

    out: list[str] = []
    out.append(f"## Week of {start} → {end}")
    out.append("")
    out.append(
        f"**{total} new citation{'s' if total != 1 else ''}** across **{len(by_paper)} paper{'s' if len(by_paper) != 1 else ''}**"
        + (f" · {self_cites} self-citation{'s' if self_cites != 1 else ''}" if self_cites else "")
    )
    out.append("")

    for paper_id, rows in ranked:
        paper = papers_by_id.get(paper_id, {})
        title = paper.get("title") or "(untitled)"
        link = paper.get("link", "")
        heading = f"### [{title}]({link}) — +{len(rows)}" if link else f"### {title} — +{len(rows)}"
        out.append(heading)
        if paper.get("venue") or paper.get("year"):
            out.append(f"_{', '.join(filter(None, [paper.get('venue'), str(paper.get('year') or '')]))}_")
        out.append("")
        for row in rows:
            citing_title = row.get("citing_title") or "(untitled)"
            citing_link = row.get("citing_link") or ""
            authors = row.get("citing_authors") or ""
            venue = row.get("citing_venue") or ""
            year = row.get("citing_year")
            suffix_parts = [p for p in [authors, venue, str(year) if year else ""] if p]
            suffix = f" — {' · '.join(suffix_parts)}" if suffix_parts else ""
            mark = " 🔁" if is_self_citation(authors, surname_re) else ""
            if citing_link:
                out.append(f"- [{citing_title}]({citing_link}){suffix}{mark}")
            else:
                out.append(f"- {citing_title}{suffix}{mark}")
        out.append("")

    out.append("---")
    out.append("_Generated by [Scholar Monitor](https://github.com/). Set `weekly_digest: false` in `config.json` to stop these._")

    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
